export const testimonials = [
    { author: 'Giulia Rossi', job: 'Content Creator', content: 'SEOLO ha raddoppiato le visite in pochi mesi! Un successo garantito per noi.👍', date: '05 maggio 2025', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Luca Bianchi', job: 'Copywriter Freelance', content: 'Interfaccia intuitiva, risultati concreti. Software eccellente per ogni mia esigenza.💯', date: '12 aprile 2025', feedback: '⭐⭐⭐⭐' },
    { author: 'Maria Conti', job: 'SEO Specialist', content: 'Supporto clienti eccellente, software facile da usare. Consigliatissimo a tutti i professionisti.😊', date: '28 marzo 2025', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Marco Verdi', job: 'Blogger Professionista', content: 'Le funzionalità intelligenti avanzate mi hanno sorpreso. Un vero game changer.🎉', date: '15 febbraio 2025', feedback: '⭐⭐⭐⭐' },
    { author: 'Anna Villa', job: 'Marketing Manager', content: 'Perfetto in crescita, lo consiglio vivamente! Un investimento che ripaga rapidamente.🤩', date: '01 gennaio 2025', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Fabio Marini', job: 'Consulente Web Marketing', content: 'Incremento del 150% nel traffico! Grazie SEOLO, un risultato davvero eccezionale.👍', date: '22 dicembre 2024', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Elena Greco', job: 'Analista SEO', content: 'La dashboard è intuitiva e facilissima. Ottimo strumento per monitorare performance SEO.😊', date: '10 novembre 2024', feedback: '⭐⭐⭐⭐' },
    { author: 'Matteo Neri', job: 'Redattore Editoriale', content: 'Ottimo supporto tecnico, servizio clienti perfetto. Risorsa indispensabile ogni giorno.💯', date: '03 ottobre 2024', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Sofia Lorsa', job: 'Digital PR Specialist', content: 'Software di grande aiuto per scrivere articoli e decisioni strategiche efficaci.', date: '18 settembre 2024', feedback: '⭐⭐⭐⭐' },
    { author: 'Davide Russo', job: 'Imprenditore Digitale', content: 'Lo consiglio per chi vuole risultati concreti. SEOLO è la chiave del successo.', date: '05 agosto 2024', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Chiara Romano', job: 'Web Content Editor', content: 'Perfetta stabilità e velocità di caricamento. Lavorare con SEOLO è un piacere.😊', date: '20 luglio 2024', feedback: '⭐⭐⭐⭐' },
    { author: 'Andrea Eseti', job: 'Specialista Marketing Contenuti', content: 'Funziona benissimo anche su mobile. Accessibile ovunque, sempre pronto all\'uso.📱', date: '12 giugno 2024', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Vale Sale', job: 'Giornalista Online', content: 'Personalizzazione avanzata fantastica. Creare contenuti unici non è mai stato così facile.', date: '01 maggio 2024', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Alessia Ferri', job: 'Seo Copywriter', content: 'SEOLO mi ha permesso di conquistare la prima pagina di Google in poche settimane!😊', date: '20 maggio 2025', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Beatrice Colpe', job: 'Consulente Contenuti', content: 'Ottimo strumento per scrivere articoli SEO. Interfaccia semplicissima. Un must-have!😊', date: '15 aprile 2025', feedback: '⭐⭐⭐⭐' },
    { author: 'Carlo Russo', job: 'Community Manager', content: 'I feedback immediati mi aiutano a monitorare l\'articolo in tempo reale, fantastico.✨', date: '02 aprile 2025', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Daniela Remi', job: 'Growth Hacker', content: 'Grazie ai suggerimenti di SEOLO, il nostro bounce rate è calato del 40%.😊', date: '25 marzo 2025', feedback: '⭐⭐⭐⭐' },
    { author: 'Edoardo Lopa', job: 'Product Manager Digitale', content: 'Integrazione perfetta con i nostri articoli esistenti. Un vero valore aggiunto per il team.', date: '10 febbraio 2025', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Elia Galli', job: 'Responsabile E-commerce', content: 'La funzione di tracciamento dei link è precisa. Bravissimi! Ottimo per l\'analisi.🎉', date: '28 gennaio 2025', feedback: '⭐⭐⭐⭐' },
    { author: 'Gabry Neri', job: 'Strategist Contenuti', content: 'Supporto rapido e sempre disponibile, un vero plus. Clienti soddisfatti!🎉🎉', date: '05 gennaio 2025', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Ilaria Santi', job: 'Autrice Web', content: 'I moduli di formazione sono molto utili per capire come scrivere un ottimo articolo.😊', date: '15 dicembre 2024', feedback: '⭐⭐⭐⭐' },
    { author: 'Lorenzo Vitale', job: 'Analista di Marketing', content: 'Performance rapide, interfaccia intuitiva su desktop e mobile.', date: '30 novembre 2024', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Martina Russo', job: 'Gestore di Blog Aziendale', content: 'Le notifiche in tempo reale ci permettono di agire subito sui problemi. Essenziale.🔔', date: '10 novembre 2024', feedback: '⭐⭐⭐⭐' },
    { author: 'Nicola Pota', job: 'Esperto di Content Marketing', content: 'Le funzionalità di esporta articolo dopo la SEO è fantastica. Risparmio tempo.😊', date: '22 ottobre 2024', feedback: '⭐⭐⭐⭐⭐' },
    { author: 'Olga Baci', job: 'Responsabile Editoriale', content: 'Estremamente flessibile e personalizzabile secondo le mie esigenze. Lo adoro! 🎉', date: '05 settembre 2024', feedback: '⭐⭐⭐⭐' },
    { author: 'Paolo Conti', job: 'Consulente SEO', content: 'Mi ha aiutato a raddoppiare il traffico organico in meno di 3 mesi.🎉 Incredibile!', date: '18 agosto 2024', feedback: '⭐⭐⭐⭐⭐' },
];
